### ISSUE TITLE
Problem with SightAngle Method

### ISSUE THREAD

**Issue by SteVentis** [gehtsoft-usa/BallisticCalculator1#43]
The SighAngle method in TrajectoryCalculator keeps throwing the  InvalidOperationException at the end while the values of the model properties are valid according to the documentation.

Model Example:
`
{
  "drag": "G1",
  "ballisticCoefficient": 0.404,
  "bulletWeight": 150,
  "bulletLength": 2.827,
  "bulletDiameter": 0.782,
  "muzzleVelocity": 830,
  "zeroRange": 100,
  "sightHeight": 5.35,
  "twistRate": 25.4,
  "riflingDirection": 1,
  "avgWindSpeed": 1,
  "windDirection": 90,
  "temperature": 15,
  "pressure": 1013.21,
  "humidity": 0,
  "pressureAtSeaLevel": true,
  "altitude": 0,
  "step": 50,
  "maximumDistance": 1000
}
`

`
public Rifle ForRifleAndScopeData(double sightHeight, double rifleTwists, RiflingDirection riflingDirection, int zeroDistance)
        {
            Sight sight = new()
            {
                SightHeight = new Measurement<DistanceUnit>(sightHeight, DistanceUnit.Centimeter)
            };
            Rifling rifling = new()
            {
                RiflingStep = new Measurement<DistanceUnit>(rifleTwists, DistanceUnit.Centimeter),
                Direction = (TwistDirection)riflingDirection
            };
            ZeroingParameters zeroing = new()
            {
                Ammunition = null,
                Atmosphere = null,
                Distance = new Measurement<DistanceUnit>(zeroDistance, DistanceUnit.Meter)
            };

            return new Rifle() { Sight = sight, Rifling = rifling, Zero = zeroing };
        }

        public ShotParameters ForShotParameters(Rifle rifle, Ammunition ammo, Atmosphere atmosphere, int step, int maxDistance)
        {
            TrajectoryCalculator calc = new TrajectoryCalculator();

            return new ShotParameters()
            {
                MaximumDistance = new Measurement<DistanceUnit>(maxDistance, DistanceUnit.Meter),
                Step = new Measurement<DistanceUnit>(step, DistanceUnit.Meter),
                SightAngle = calc.SightAngle(ammo, rifle, atmosphere)
            };
        }
`
![error](https://github.com/gehtsoft-usa/BallisticCalculator1/assets/101551480/c85edaf5-962c-4c1d-a141-b3f0a4836d8b)

**Comment by nikolaygekht** [comment]
I've created an isolated piece of the code that calculates sight angle for the paraemeters your specified:
```cs
public static void Do(String[] args)
{
    var ammo = new Ammunition()
    {
        BallisticCoefficient = new BallisticCoefficient(0.404, DragTableId.G1),
        BulletDiameter = DistanceUnit.Centimeter.New(0.782),
        BulletLength = DistanceUnit.Centimeter.New(2.872),
        Weight = WeightUnit.Grain.New(150),
        MuzzleVelocity = VelocityUnit.MetersPerSecond.New(830)
    };

    var atmo = new Atmosphere(DistanceUnit.Meter.New(0), PressureUnit.Pascal.New(101.321), TemperatureUnit.Celsius.New(15), 0);

    var rifle = new Rifle()
    {
        Rifling = new Rifling()
        {
            Direction = TwistDirection.Right,
            RiflingStep = DistanceUnit.Centimeter.New(25.4),
        },
        Sight = new Sight()
        {
            SightHeight = DistanceUnit.Centimeter.New(5.35),
        },
        Zero = new ZeroingParameters()
        {
            Distance = DistanceUnit.Meter.New(100)
        }
    };

    var calc = new TrajectoryCalculator();

    var angle = calc.SightAngle(ammo, rifle, atmo);

    Console.WriteLine("Sight Angle {0}", angle.To(AngularUnit.MOA).ToString());
}
```

It gave me `4.28703593649454moa` that looks pretty much realistic. 

So, please:

1) Double check that all required parameters are filled from the model.

2) Double check that proper measurements unit are used (unfortunately, I cannot check it from the code you shown).

If it doesn't help, please create an isolated piece of code that I can execute as a function so I can reproduce the defect. 

Thanks!

**Comment by nikolaygekht** [comment]
The author confirmed privately that code example helped to find the problem in the code. 
Closing issue, but I'll consider better diagnostic

**Comment by SteVentis** [comment]
Sorry to post a little late. I had made a mistake at the values of atmosphere data. I used mbar instead of bar. Your example helped me find it. The program is very simple to use and thank you again for your work and your help.
